### ISSUE TITLE
エラー負けの際の対応

### ISSUE THREAD

**Issue by umiwatarin** [KPC-U16/CHaserRuleGuide-Pub#9]
選手は1試合につき、エラー負けと判定された場合に偶発的な問題であると思われるときは、1度だけ再試合を要求できる。
再試合が要求され、審判長が要求を許可した場合、マップを変更して再試合を行う。

**Comment by noko1024** [comment]
偶発的な問題をどのように定義するか
制限された時間の中でどう判断するか
が問題では

**Comment by kqnade** [comment]
- [x] 偶発的エラーの定義
- [ ] 運営の判断基準の明確化
- [ ]

**Comment by umiwatarin** [comment]
選手は1試合につき、エラー負けと判定された場合に ~~偶発的な問題である~~ ルール（何条何項に規定されているとか書く）に違反していないと思われるときは、1度だけ再試合を要求できる。
再試合が要求され、審判長が要求を許可した場合、マップを変更して再試合を行う。

**Comment by kqnade** [comment]
- 要求条件
  - サーバーが何らかの理由で試合が続行不能になった場合
  - 相手のクライアントから一定時間以内に応答がない場合
  - その他審判または運営が必要と判断した場合
 - 判断者・責任者
   - 審判、運営
 - 対応
   - マップの変更をしたうえで再戦を行う
   - 後半戦の場合はアイテム数の観点から前半戦から試合を行う
 - 備考
   - 要求条件の第2項に関しては1試合あたり1回までとする

**Comment by kqnade** [comment]
試合の進行において、以下の条件が発生した場合、再戦を行う。

1. サーバーが何らかの理由で試合の続行が不可能となった場合。
2. 相手のクライアントから一定時間以内に応答がない場合。
3. その他、審判または運営が試合の再開が不可能と判断した場合。

再戦に関する判断は、審判または運営が行うこととする。再戦を実施する場合、以下の対応を行う：

1. 試合の再開にあたっては、マップを変更したうえで再戦を実施する。
2. 後半戦の場合、アイテム数の観点から、前半戦から試合を再開する。

なお、相手のクライアントからの応答がない場合については、1試合あたり1回までとする。
